# --- OpenAI
OPENAI_API_KEY = "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"
OPENAI_MODEL = "gpt-4o-mini"

# --- App URL (pour le lien dans l’email)
APP_BASE_URL = "http://localhost:8501"

# --- Gmail SMTP
SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USER = "nguyen.valery1@gmail.com"
SMTP_PASS = "Bi@rritz64"   # <-- mot de passe d’application Gmail (obligatoire)
EMAIL_FROM = "EVERSKILLS <nguyen.valery1@gmail.com>"

[SMTP]
HOST = "ssl0.ovh.net"
PORT = 587
USE_TLS = true
USE_SSL = false
USERNAME = "contact@everboarding.fr"
PASSWORD = "Bi@rritz64"
FROM_EMAIL = "contact@everboarding.fr"
FROM_NAME = "EverSKILLS"
